trigger: none

pool: self_test

jobs:
 - job: terraforminit
   displayName: Terraform-Init
   steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'appconnecttest'
          backendAzureRmStorageAccountName: 'strgadi01'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'terraform.tfstate'

 - job: terraformplan
   displayName: Terraform-Plan
   dependsOn: terraforminit
   steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'appconnecttest'