trigger: main

jobs:
- job: terraforminitplan
  displayName: terraform init and plan job
  pool: self_test
  steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
      backendServiceArm: 'appconnecttest'
      backendAzureRmStorageAccountName: 'testadtest01'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'terraform.tfstate'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
      environmentServiceNameAzureRM: 'appconnecttest'

- job: manualvalidation
  displayName: manual validation
  dependsOn: terraforminitplan
  pool: server
  steps:
    - task: ManualValidation@1
    inputs:
      notifyUsers: 'tiwari.aditi1020@gmail.com'
      approvers: 'tiwari.aditi1020@gmail.com'
      instructions: 'check plan'

- job: terraformapply
  displayName: terrafrom apply wala job
  dependsOn: manualvalidation
  pool: self_test
  steps:
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
      environmentServiceNameAzureRM: 'appconnecttest'