trigger:
  branches:
    include:
      - main

jobs:
- job: terraforminitplan
  displayName: Terraform Init and Plan
  pool: self_test
  steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
      backendServiceArm: 'appconnecttest'
      backendAzureRmStorageAccountName: 'testadtest01'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'terraform.tfstate'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
      environmentServiceNameAzureRM: 'appconnecttest'

- job: manualvalidation
  displayName: Manual Validation
  dependsOn: terraforminitplan
  pool: server
  steps:
  - task: ManualValidation@1
    inputs:
      notifyUsers: 'rahulgtripathi@gmail.com'
      approvers: 'rahulgtripathi@gmail.com'
      instructions: 'check please'

- job: TerraformApply
  displayName: Terraform Apply
  dependsOn: manualvalidation
  pool: self_test
  steps:
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
      environmentServiceNameAzureRM: 'appconnecttest'
